contact_links:
    - name: ❓ Questions and Help 🤔
      url: https://discord.com/invite/c79mzZnu
      about: This issue tracker is not for support questions. Please refer to the community for more help. 
